version: "3.9"
services:
  project1:
    build:
      context: .
      dockerfile: Dockerfile
    command: "tail -f /dev/null"
    volumes:
      - ./arcdevelopment:/home/node/material-ui/project1
    ports:
      - "3000:3000"